### ISSUE TITLE
[Enhance]Tax detection switch (optional)

### ISSUE THREAD

**Issue by kugimiya530** [tsarbuig/Limit-Sniper-V3#5]
for example

if the token buy tax was 10%   but  sell tax  was high  like  60%

then, if sniper can have a switch 

we can detect buy+sell tax in same block

but, it's optional not too important

**Comment by tsarbuig** [comment]
I don't understand ? can you explain more ?

**Comment by kugimiya530** [comment]
For example

There is a token when launch buy tax=10%

Sell tax=90%

For this condition I set maxtax=(any number above10) sniper will buy but
can get any profit due to there is 90% sell tax

If u can set a switch in parameter to change detection logic will be good

Example

"Parameter.json"

Maxtax.detection.both = true/false

If true then maxfee will cal the tax which buy+sell

If false only detect the buy tax

TsarBuig ***@***.***> 於 2023年2月7日 週二 上午5:34 寫道：

**Comment by kugimiya530** [comment]
Anyway was optional

Not the most important issue
