### ISSUE TITLE
[Enhance]multiwallet without custom contract

### ISSUE THREAD

**Issue by kugimiya530** [tsarbuig/Limit-Sniper-V3#8]
is it possible using multiwallet without custom contract due to there is some contract (not many) code has "tx.origin" etc.. will make custom contract don't work
(i know this option will destory all the sniper logic from now  need to import all the private key etc.., so i put it  last, i guess this option will reject i think so ， even i am not good at programing i know it will destory everything like brain 😂)

**Comment by tsarbuig** [comment]
you mean some contracts will make your Tx fail if tx "from" is different than tx "to" ?

**Comment by kugimiya530** [comment]
yep  like  tx.origin

or something like that

TsarBuig ***@***.***> 於 2023年2月12日 週日 上午5:46寫道：
